# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  dummyapi:
    image: dummyapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 7078:7078
      - 443:443
      - 80:80
